Resources:
  OrderKpisTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: order_kpis
      AttributeDefinitions:
        - AttributeName: order_date
          AttributeType: S
      KeySchema:
        - AttributeName: order_date
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  CategoryKpisTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: category_kpis
      AttributeDefinitions:
        - AttributeName: category
          AttributeType: S
        - AttributeName: order_date
          AttributeType: S
      KeySchema:
        - AttributeName: category
          KeyType: HASH
        - AttributeName: order_date
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
