spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.path.style.access=true
spark.hadoop.fs.s3a.endpoint=s3.amazonaws.com
spark.hadoop.fs.s3a.aws.credentials.provider=com.amazonaws.auth.DefaultAWSCredentialsProviderChain
spark.jars.ivy=/tmp/.ivy2
spark.hadoop.mapreduce.fileoutputcommitter.algorithm.version=2

# ADD THIS LINE: Explicitly tell Spark to load these JARs
spark.jars=/opt/bitnami/spark/jars/hadoop-aws-3.3.6.jar,/opt/bitnami/spark/jars/aws-java-sdk-bundle-1.12.525.jar